# Generated by Django 5.0.1 on 2024-02-03 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日")),
                ("end_date", models.DateField(verbose_name="終了日")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("家庭からの給付", "家庭からの給付"),
                            ("日本学生支援機構の奨学金", "日本学生支援機構の奨学金"),
                            (
                                "日本学生支援機構以外の奨学金",
                                "日本学生支援機構以外の奨学金",
                            ),
                            ("アルバイト等収入", "アルバイト等収入"),
                            ("その他", "その他"),
                        ],
                        max_length=30,
                        verbose_name="カテゴリー",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="1万円未満は切り捨てて入力してください。",
                        max_digits=2,
                        verbose_name="金額（単位：万円）",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
